/*
Even Fibonacci numbers
Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

#include "stdafx.h"
#include <iostream>
#include <vector>

int euler_02()
{
	std::vector<int> fibs;
	fibs.push_back(1);
	fibs.push_back(2);
	while (fibs.back() < 4000000)
	{
		int last = fibs.back();
		int sec_last = fibs[fibs.size() - 2];
		fibs.push_back(last + sec_last);
	}
	int answer = 0;
	for (int i = 0; i < fibs.size() -1 ; i++)
	{
		if ((fibs[i] % 2) == 0)
		{
			answer += fibs[i];
		}
	}

	return answer;
}